# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_auto_20170510_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='Address', max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
