# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_auto_20170807_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
