# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcion', models.IntegerField(verbose_name='Porción')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Detalles',
                'verbose_name': 'Detalle',
            },
        ),
        migrations.CreateModel(
            name='InsumosDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.Detalle')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.Producto')),
            ],
            options={
                'verbose_name_plural': 'InsumosDetalles',
                'verbose_name': 'InsumosDetalle',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'verbose_name': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TipoMenus',
                'verbose_name': 'TipoMenu',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='tipo_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.TipoMenu'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Menu', verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.Receta'),
        ),
    ]
