# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_menu_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumosdetalle',
            options={'verbose_name': 'Insumos Detalle', 'verbose_name_plural': 'Insumos Detalles'},
        ),
        migrations.AddField(
            model_name='menu',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='insumosdetalle',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Detalle'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
