# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20170914_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
