# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'verbose_name': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Ingredientes',
                'verbose_name': 'Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recetario.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('porcion', models.IntegerField(verbose_name='Porción')),
                ('preparacion', models.TextField(verbose_name='Preparación')),
                ('imagen', models.ImageField(blank=True, upload_to='recetas', verbose_name='Imágen')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recetas',
                'verbose_name': 'Receta',
            },
        ),
        migrations.CreateModel(
            name='TipoReceta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo Recetas',
                'verbose_name': 'Tipo Receta',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('simbolo', models.CharField(default='Und', max_length=10, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'verbose_name': 'Unidad',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='tipo_receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.TipoReceta', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.Unidad'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.Producto'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetario.Receta'),
        ),
    ]
