# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_auto_20170723_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetario.Receta'),
        ),
    ]
