# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_auto_20170914_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.Receta'),
        ),
    ]
