# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_auto_20170828_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
