# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0004_auto_20170905_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
